CREATE DATABASE DB_ORDERCONTROL;

USE DB_ORDERCONTROL;

CREATE TABLE IF NOT EXISTS TB_CADASTRO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    SENHA VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    IDADE INT NOT NULL,
    CPF INT NOT NULL,
    ADMIN INT NOT NULL,
    SEXO VARCHAR(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_EVENTOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TIPOEVENTO INT NOT NULL,
    NOMECLIENTE VARCHAR(200) NOT NULL,
    LOCAL VARCHAR(200) NOT NULL,
    DATA VARCHAR(200) NOT NULL,
    HORA VARCHAR(200) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    ID_USUARIO1 INT,
    ID_USUARIO2 INT
);